[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PQAnalysis"
version = "0.0.1"
authors = [
  { name="Jakob Gamper", email="97gamjak@gmail.com" },
  { name="Josef M. Gallmetzer", email="" },
]
description = "PQAnalysis is a python package for the analysis of PIMD-QMCF simulations."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/97gamjak/PQAnalysis"
"PIMD-QMCF" = "https://github.com/97gamjak/pimd_qmcf"