[build-system]
requires = ["setuptools>=42", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "PQAnalysis"
dynamic = [
    "version"
]
authors = [
  { name="Jakob Gamper", email="97gamjak@gmail.com" },
  { name="Josef M. Gallmetzer", email="gallmetzer.josef@gmail.com" },
]
description = "PQAnalysis is a python package for the analysis of PIMD-QMCF simulations."
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    'numpy',
    "beartype",
    "multimethod",
]

[project.optional-dependencies]
test = [
    "pytest",
    "coverage",
    "pytest-cov"
]

[tool.setuptools_scm]
version_file = "PQAnalysis/_version.py"

[project.scripts]
traj2box = "PQAnalysis.cli.traj2box:main"
traj2qmcfc = "PQAnalysis.cli.traj2qmcfc:main"

[project.urls]
"Homepage" = "https://github.com/97gamjak/PQAnalysis"
"PIMD-QMCF" = "https://github.com/97gamjak/pimd_qmcf"
